SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCTS.CATEGORY_ID, CATEGORIES.CATEGORY_ID, CATEGORY_NAME, DESCRIPTION 
FROM PRODUCTS, CATEGORIES 
WHERE PRODUCTS.CATEGORY_ID=CATEGORIES.CATEGORY_ID;

SELECT PRODUCT_ID, PRODUCT_NAME, P.CATEGORY_ID, C.CATEGORY_ID, CATEGORY_NAME, DESCRIPTION 
FROM PRODUCTS P, CATEGORIES C
WHERE P.CATEGORY_ID=C.CATEGORY_ID;

SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY_NAME, DESCRIPTION 
FROM PRODUCTS P, CATEGORIES C
WHERE P.CATEGORY_ID=C.CATEGORY_ID;


SELECT PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, CATEGORY_NAME, COMPANY_NAME AS SUPPLIER_NAME
FROM PRODUCTS P 
    JOIN CATEGORIES C
        ON P.CATEGORY_ID=C.CATEGORY_ID
    JOIN SUPPLIERS S
        ON P.SUPPLIER_ID=S.SUPPLIER_ID
WHERE UNIT_PRICE BETWEEN 10 AND 20
ORDER BY UNIT_PRICE;

SELECT O.ORDER_ID, 
    C.COMPANY_NAME AS CUSTOMER,
    CONCAT(E.TITLE_OF_COURTESY, E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE,
    O.ORDER_DATE,
    O.REQUIRED_DATE,
    S.COMPANY_NAME AS SHIPPED_BY
FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMER_ID=C.CUSTOMER_ID
JOIN EMPLOYEES E ON O.EMPLOYEE_ID=E.EMPLOYEE_ID
JOIN SHIPPERS S ON O.SHIP_VIA=S.SHIPPER_ID;



SELECT PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, CATEGORY_NAME
FROM PRODUCTS 
NATURAL JOIN CATEGORIES;

SELECT O.ORDER_ID, S.COMPANY_NAME AS SHIPPED_BY
FROM ORDERS O
NATURAL JOIN SHIPPERS S; -- NO COMMON COLUMN BETWEEN THESE TWO TABLES; RESULTS IN CARTESIAN PRODUCT.


SELECT O.ORDER_ID, 
    CONCAT(E.TITLE_OF_COURTESY, E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE,
    O.ORDER_DATE,
    O.REQUIRED_DATE
FROM ORDERS O
NATURAL JOIN EMPLOYEES E;

SELECT CATEGORIES.CATEGORY_ID, CATEGORY_NAME, PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE
FROM CATEGORIES LEF JOIN PRODUCTS
    ON CATEGORIES.CATEGORY_ID=PRODUCTS.CATEGORY_ID
ORDER BY CATEGORIES.CATEGORY_ID;

SELECT CATEGORIES.CATEGORY_ID, CATEGORY_NAME, PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE
FROM PRODUCTS RIGHT JOIN CATEGORIES
    ON CATEGORIES.CATEGORY_ID=PRODUCTS.CATEGORY_ID
ORDER BY CATEGORIES.CATEGORY_ID;


SELECT CATEGORIES.CATEGORY_ID, CATEGORY_NAME, PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE
FROM CATEGORIES FULL OUTER JOIN PRODUCTS
    ON CATEGORIES.CATEGORY_ID=PRODUCTS.CATEGORY_ID
ORDER BY CATEGORIES.CATEGORY_ID;


SELECT EMP.EMPLOYEE_ID, CONCAT_WS(' ', EMP.FIRST_NAME, EMP.LAST_NAME) AS EMPLOYEE_NAME,
    MGR.EMPLOYEE_ID, CONCAT_WS(' ', MGR.FIRST_NAME, MGR.LAST_NAME) AS MANAGER_NAME
FROM EMPLOYEES AS EMP
LEFT JOIN EMPLOYEES AS MGR
ON EMP.REPORTS_TO = MGR.EMPLOYEE_ID;

-- DISPLAY ALL PRODUCTS THAT HAVE PRICE >= THAT OF 'Schoggi Schokolade'

SELECT P1.*
FROM PRODUCTS P1
JOIN PRODUCTS P2 ON P1.UNIT_PRICE >= P2.UNIT_PRICE
WHERE P2.PRODUCT_NAME='Schoggi Schokolade';


SELECT DISTINCT CATEGORY_ID FROM PRODUCTS WHERE SUPPLIER_ID=6;

SELECT * FROM PRODUCTS WHERE CATEGORY_ID IN (SELECT DISTINCT CATEGORY_ID FROM PRODUCTS WHERE SUPPLIER_ID=6);

