GET /my-webapp/api/greeting
Host: localhost:8080
Accept: application/json

###

GET /
Host: localhost:8080
Accept: text/plain


###

GET /api/customers
Host: localhost:8080
Accept: application/json

###
GET /api/customers/0eb31b3d-dde3-4138-9c6e-124fe7264278
Host: localhost:8080
Accept: application/json

###
GET /api/customers/0eb31b3d-dde3-4138-9c6e-124fe7264000
Host: localhost:8080
Accept: application/json

###
POST /api/customers
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
    "name": "Kishore Kumar",
    "city": "Mumbai",
    "email": "asdf@xmpl.com",
    "phone": "9731412334"
}

###

GET /api/customers/9e25b493-b764-46ee-a411-f413f1ee3973
Host: localhost:8080
Accept: application/json


# Tasks for Day 22: Implement these handlers in the CustomersController

###
GET /api/customers
Host: localhost:8080
Accept: application/json

### with put request, you have to supply entire object with some modification
PUT /api/customers/0eb31b3d-dde3-4138-9c6e-124fe7264278
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
  "name": "Shyam Sundar",
  "email": "shyam@xmpl.com",
  "phone": "9008007006",
  "city": "Mysuru"
}

### with patch, you can send only those fields that need to be updated
PATCH /api/customers/0eb31b3d-dde3-4138-9c6e-124fe7264278
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
    "city": "Mysore"
}

### 
DELETE /api/customers/8bec3fb4-ae9e-423e-95c1-aef2d6ddd093
Host: localhost:8080
Accept: application/json